language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install tcl
  - sudo apt-get install tk
  - sudo apt-get install julia -y
  - sudo apt-get install libXxf86vm-dev # GLFW dependencies
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd())'
  - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'Pkg.test("OpenStreetMap", coverage=true)'; fi
  - if [ $JULIAVERSION = "juliareleases" ]; then julia -e 'Pkg.test("OpenStreetMap")'; fi
after_success:
    - if [ $JULIAVERSION = "julianightlies" ]; julia -e 'cd(Pkg.dir("OpenStreetMap")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
