language: julia
os:
  - linux
julia:
  - 0.4
  - 0.3
sudo: required
notifications:
  email: false
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install tcl
  - sudo apt-get install tk
  - sudo apt-get install libXxf86vm-dev # GLFW dependencies
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.test("OpenStreetMap", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("OpenStreetMap")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("OpenStreetMap")); using Coverage; Codecov.submit(Codecov.process_folder())'
