language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install tcl
  - sudo apt-get install tk
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install libXxf86vm-dev # GLFW dependencies
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("OpenStreetMap"))`); Pkg.pin("OpenStreetMap"); Pkg.resolve()'
  - julia -e 'using OpenStreetMap; @assert isdefined(:OpenStreetMap); @assert typeof(OpenStreetMap) === Module'
